### ISSUE TITLE
Consider switching to superagent-mock from nock for tests

### ISSUE THREAD

**Issue by j3parker** [Brightspace/superagent-d2l-session-auth#25]
I find the HTTP mocking to be frustrating because I'm never really sure that what I want to test is what I'm testing. This could be due to my JS noobishness.

[https://github.com/M6Web/superagent-mock](superagent-mock) seems like it could be better for tests. Maybe.

**Comment by cpacey** [comment]
Just FYI, part of why I chose Nock at the beginning was to make things an integration test with superagent.  I.e. instead of mocking out the guts of superagent, I wanted to mock out the XHR results and let superagent handle that.  This was intentional to ensure that superagent was actually behaving like I expected it to.

**Comment by j3parker** [comment]
That's a fair point - we are using superagent in a weird way.
